export const FETCH_POKEMONS_PENDING = "FETCH_POKEMONS_PENDING";
export const FETCH_POKEMONS_SUCCESS = "FETCH_POKEMONS_SUCCESS";
export const FETCH_POKEMONS_ERROR = "FETCH_POKEMONS_ERROR";
export const FILTER_POKEMONS = "FILTER_POKEMONS";
export const FETCH_POKEMON_DATA = "FETCH_POKEMON_DATA";
