const Types = {
  FETCH_POKEMONS_PENDING: "FETCH_POKEMONS_PENDING",
  FETCH_POKEMONS_SUCCESS: "FETCH_POKEMONS_SUCCESS",
  FETCH_POKEMONS_ERROR: "FETCH_POKEMONS_ERROR",
  FILTER_POKEMONS: "FILTER_POKEMONS",
  FETCH_POKEMON_DATA: "FETCH_POKEMON_DATA",
  SET_OFFSET: "SET_OFFSET",
};

export default Types;
